# Custom Language File for Launcher Customizer

[ejs.app]
title = "Evimeria Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "https://x.com/VonDefiant12"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@vondefiant2259"
mediaDiscordURL = "https://discord.gg/C7US3zgPxj"

[ejs.settings]
sourceGithubLink = "https://github.com/VonDefiant/EVIMERIA-LAUNCHER"
supportLink = "https://github.com/VonDefiant/EVIMERIA-LAUNCHER/issues"

[ejs.welcome]
welcomeHeader = "Bienvenido a Evimeria Launcher"
welcomeDescription = "Este launcher te hara m√°s facil las configuraciones."
welcomeDescCTA = "Diviertete."
